
# 工作流名称
name: web-CI

# 限定工作流执行的条件
# 触发条件 branches限定分支
# push推送到master动作

on:
  push:
    branches:
      - master

# 一个工作流的根节点jobs,以下可以定义多个job
jobs:
  # 定义一个名为 build 的job
  build:
    # CI 或 job执行的环境
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    # job中每一步的任务序列
    steps:
    # Job Start
    - name: Job Start
      run: echo Hello, GitHub workflows !
    # 检出你在当前github工作空间的项目
    - uses: actions/checkout@v2
    # 执行一个一系列或多行的shell命令
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.

    # 设置Node环境 actions/setup-node@v1 是GitHub Marketplace其中的一个,相当于一个方法
    # 使用一个Actions 使用uses关键字,  with表明参数
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        # The name of the image you would like to push
        # name: ${{secrets.DOCKER_PROGRAM}}
        name: lvdongliangtest/vuenginxcontainertencent
        # The login username for the registry
        username: ${{secrets.DOCKER_USERNAME_TENCENT}}
        # The login password for the registry
        password: ${{secrets.DOCKER_PASSWORD_TENCENT}}
          # Use registry for pushing to a custom registry
        registry: ${{secrets.DOCKER_REGISTRY_TENCENT}}
    - name: ssh docker login # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_TENCENT }} 
        username: ${{ secrets.SSH_USERNAME_TENCENT }}
        password: ${{ secrets.SSH_PASSWORD_TENCENT }}
        script: cd ~/sh && sh deploy.sh ${{ secrets.DOCKER_USERNAME_TENCENT }} ${{ secrets.DOCKER_PASSWORD_TENCENT }}